name: Update Predictions CSV

on:
  schedule:
    - cron: "49 22 * * *" # 10:49 PM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-predictions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scikit-learn numpy pandas

    - name: Run Predictions
      run: |
        cd Models
        python RandomForest.py 

    - name: Commit and Push CSV Updates
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        
        # Check if there are changes to commit
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit. Exiting."
          exit 0
        fi
        
        git add Front/CSVFiles/prediction_results.csv Front/CSVFiles/win_loss_records.csv
        git commit -m "Update predictions and win-loss records CSVs [automated]"
        git push
